#!/usr/bin/python

import sys
import os,shutil,tempfile

sep = '#'

#shutil.copy2(sys.argv[1],'temp1.dat')
#shutil.copy2(sys.argv[2],'temp2.dat')

fileAvariableList = sys.argv[1]+'/setup_data/variable_list.arb'
fileBvariableList = sys.argv[2]+'/setup_data/variable_list.arb'

fileAoutput = sys.argv[1]+'/output.scr'
fileBoutput = sys.argv[2]+'/output.scr'

# dalton python OMG
if os.path.isfile(fileAoutput) and os.path.isfile(fileBoutput):
    includenumerical = 1
else:
    includenumerical = 0
    print ('WARNING: numerical results not included in comparison as output.scr files not available')

outfile = open('tempA.dat','w')

if includenumerical:
    infile = open (fileAoutput,'r')
    for line in infile:
        if "read numerical" in line:
            print >>outfile, line

infile = open(fileAvariableList,'r')
for line in infile:
    rest = line.split(sep,1)[0]
    print >>outfile, rest
outfile.close()

outfile = open('tempB.dat','w')

if includenumerical:
    infile = open (fileBoutput,'r')
    for line in infile:
        if "read numerical" in line:
            print >>outfile, line

infile = open(fileBvariableList,'r')
for line in infile:
    rest = line.split(sep,1)[0]
    print >>outfile, rest
outfile.close()

os.system("diff tempA.dat tempB.dat")
    
# with open('tempA.dat', 'r') as file1:
#     with open('tempB.dat', 'r') as file2:
#         diff = set(file1).difference(file2) #CAN USE INTERSECTION HERE FOR COMMON ELEMENTS

# diff.discard('\n')

# with open('diff.txt', 'w') as file_out:
#     for line in diff:
#         file_out.write(line)


#os.remove('tempA.dat')
#os.remove('tempB.dat')
