# acl.auth.php
# <?php exit()?>
# Don't modify the lines above
#
# Access Control Lists
#
# Auto-generated by install script
# Date: Sun, 23 Aug 2015 12:45:47 +0000
*               @ALL          0
*               @user         8
