<?php
/*
 * Siteexport Cron Job Configuration
 * Auto-generated by siteexport
 * Run for user: daltonh
 */

// Required to set the HTTP_HOST which is usually not set in CLI Environments 
$_SERVER['HTTP_HOST'] = "localhost";

// This is not the nice way to inject another ROOT-URL, but we do not want to modify other stuff. 
if(!defined('DOKU_URL')) define('DOKU_URL', "http://localhost/arb_dokuwiki/");


// end of auto-generated content