<?php
/*
 * Dokuwiki's Main Configuration File - Local Settings
 * Auto-generated by config plugin
 * Run for user: daltonh
 * Date: Tue, 25 Aug 2015 01:17:01 +1100
 */

$conf['title'] = 'arb manual';
$conf['license'] = 'gnufdl';
$conf['useacl'] = 1;
$conf['superuser'] = '@admin';
$conf['disableactions'] = 'register';
$conf['plugin']['mathjax']['config'] = 'MathJax.Hub.Config({
    tex2jax: {
        inlineMath: [ ["$","$"], ["\\\\(","\\\\)"] ],
        displayMath: [ ["$$","$$"], ["\\\\[","\\\\]"] ],
        processEscapes: true
    }
});';
$conf['plugin']['siteexport']['depth'] = 5;
$conf['plugin']['siteexport']['skipacl'] = 1;

// end auto-generated content
