#!/bin/sh
# copy this file to somewhere in your path (eq ~/bin) to use a binary version of maxima
if [ -e /Applications/Maxima.app/Contents/MacOS/Maxima ] ; then # this is for version 5.38
  /Applications/Maxima.app/Contents/MacOS/Maxima $*;
elif [ -e /Applications/Maxima.app/Contents/Resources/bin/maxima ] ; then # this is for version 5.21
  /Applications/Maxima.app/Contents/Resources/bin/maxima $*;
elif [ -e /Applications/Maxima.app/Contents/Resources/maxima.sh ] ; then # this is for version 5.24
  /Applications/Maxima.app/Contents/Resources/maxima.sh $*;
else
  echo 'Maxima exectuable is not found.  Have you installed Maxima.app in /Applications?';
fi
